---
- hosts: 172.31.36.60
  tasks:
    - name: cleaning files
      shell: rm -rf ~/test2

    - name: pull
      shell: git clone -b master https://github.com/Saumil343/test2.git

    - name: docker kill
      shell: docker stop nodeapp2 || true && docker rm nodeapp2 || true
    
    - name: docker build
      shell: docker build -t saumil343/demoapp4 ~/test2/
      
    - name: docker run 
      shell: docker run -it -d --name nodeapp2 -p 3000:3000 saumil343/demoapp4
